spring:
  application:
    name: eureka-client
server:
  port: 9100
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
#  instance:
#    prefer-ip-address: true