spring:
  application:
    name: eureka-server
server:
  port: 8000
eureka:
  instance:
    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8001/eureka/
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false



