spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JaylenLiu/springcloud-demo.git
          searchPaths: Configserver/src/main/resources/config
          username: JaylenLiu
          password: Liu616620
  security:
    user:
      name: user
      password: 123456
server:
  port: 8100
#security:
#  basic:
#    enabled: false
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

# 刷新总线
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
